config/routes.rb
Rails.application.routes.draw do
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'

  #static pages
  root 'static#home'

  #users
  devise_for :users, controllers: {registrations: 'registrations'}

  #posts
  post 'posts/add_attendant'
  delete 'posts/remove_attendant'
  get 'posts/autocomplete_user_name'
  get 'posts/autocomplete_city_name'
  get 'posts/invite'
  post 'posts/send_invitation'
  resources :posts
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/city.rb
class City < ActiveRecord::Base
end

app/models/concerns/filterable.rb
module Filterable extend ActiveSupport::Concern

module ClassMethods
  #filters results of query using scopes present in filtering_params
  def filter(filtering_params)
    results = self.where nil
    filtering_params.each do |k, v|
      results = results.public_send k, v if v.present?
    end
    results
  end
end
end

app/models/post.rb
class Post < ActiveRecord::Base
  include Filterable

  mount_uploader :picture, PictureUploader

  belongs_to :user
  has_and_belongs_to_many :users
  belongs_to :category
  belongs_to :city

  validates_presence_of :time, :description, :city, :user, :category, :locality
  validates :description, length: {minimum: 10}
  validates :locality, length: {minimum: 5}

  validates_processing_of :picture

  attr_accessor :attendants, :city_name, :time_from, :time_to, :event_name, :time_at

  scope :event_name, -> (name) { where 'lower(posts.name) like ?', "%#{name.downcase}%" }
  scope :category_id, -> (id) { where category_id: id }
  scope :city_name, -> (name) { joins(:city).where 'cities.name like ?', "#{name}%" }
  scope :time_from, -> (time) { where 'posts.time >= ?', time }
  scope :time_to, -> (time) { where 'posts.time <= ?', time }
  scope :attendants, -> (attendants) { joins(:users).where 'users.name in (?)', attendants }

  after_find do
    self.time_at = DateTime.strptime self.time.to_s, '%s'
    self.city_name = self.city.name
  end

  before_validation do
    self.limited = self.limit > 0
    self.time = self.time_at.to_datetime.to_i unless self.time_at.nil?
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_and_belongs_to_many :posts

  validates_uniqueness_of :email, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include ApplicationHelper
  include PostsHelper

  before_action :build_post_filter

  def render_404
    respond_to do |format|
      format.html { render :file => "/public/404.html", :status => 404 }
      format.js { render :file => "/public/404.html", :status => 404 }
    end
  end

  def redirect_back(backup_location=root_path)
    redirect_to ((request.referer) ? (request.referer) : (backup_location))
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :add_attendant, :invite, :send_invitation]
  before_action :load_post, only: [:show, :add_attendant, :remove_attendant, :edit, :update, :invite, :send_invitation]
  before_action :authenticate_owner, only: [:update, :destroy, :edit]
  before_action :validate_remove_attendant, only: :remove_attendant
  before_action :validate_add_attendant, only: :add_attendant

  def index
    if params[:search].nil?
      @posts = Post.filter(post_search_params(params[:post])).paginate page: params[:page], per_page: 9
    else
      @posts = Post.event_name(params[:search]).paginate page: params[:page], per_page: 9
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new post_params
    @post.user_id = current_user.id
    if @post.save
      flash.now[:success] = 'Event successfuly created'
      render 'show'
    else
      flash.now[:danger] = 'Creating event failed, please correct mistakes'
      render 'new'
    end
  end

  def edit
  end

  def update
    if @post.update_attributes post_params
      flash.now[:success] = 'Event successfuly created'
      render 'show'
    else
      flash.now[:danger] = 'Creating event failed, please correct mistakes'
      render 'edit'
    end
  end

  def destroy
    if @post.delete
      flash[:success] = 'Event deleted'
      redirect_to root_path
    else
      flash.now[:danger] = 'Something went wrong, please try again'
      render 'show'
    end
  end

  def show
  end

  def send_invitation
    flash[:success] = 'Users invited'
    redirect_to @post;
  end

  def add_attendant
    @post.users << current_user
    flash[:success] = 'You are now attending the event'
    redirect_to @post
  end

  def remove_attendant
    @post.users.delete current_user
    flash[:success] = 'You are not attending the event any more'
    redirect_to @post
  end

  def autocomplete_user_name
    autocomplete_entity :name do |term|
      User.where('LOWER(name) like ? or LOWER(email) like ?', "%#{term.downcase}%", "%#{term.downcase}%").limit 10
    end
  end

  def autocomplete_city_name
    autocomplete_entity :name do |term|
      City.where('LOWER(name) like ?', "%#{term.downcase}%").limit 20
    end
  end

  private
  def post_params
    params.require(:post).permit :name, :time_at, :description, :limit, :city_id, :locality, :category_id, :picture
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  ###########
  private
  ###########

  #Override because of custom non-devise attributes
  def sign_up_params
    params.require(:user).permit  :email, :name, :password, :password_confirmation
  end

  #Override because of custom non-devise attributes
  def account_update_params
    params.require(:user).permit  :email, :name, :password, :password_confirmation, :current_password
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
    @posts = Post.order(time: :desc).limit 3
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def redirect_unauthorized
    flash[:danger] = 'Unauthorized access - permission denied'
    redirect_to root_path
  end

  #verifies if logged in user is user provided in argument
  #arguments accepted are: User class instance or user id
  def current_user? (user)
    if current_user
      return (current_user.id == user.id) if user.class == User
      return (current_user.id == user) if user.class == Fixnum
    end
    false
  end

  def autocomplete_entity(method, additional_data=[], &block)
    term = params[:term]
    if term && !term.empty?
      items = yield term
    else
      items = {}
    end
    render :json => json_for_autocomplete(items, method, additional_data)
  end

  def form_errors_for(object=nil)
    render('shared/form_errors', object: object) unless object.blank? or object.errors.count == 0
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  #before actions
  def authenticate_owner
    load_post
    return if performed?
    redirect_unauthorized unless current_user? @post.user_id
  end

  def load_post
    @post = Post.find_by id: params[:id]
    render_404 if @post.nil?
  end

  def common_validate_attendant(&block)
    redirect_unauthorized if current_user.nil? or yield
  end

  def validate_remove_attendant
    common_validate_attendant { @post.users.exclude? current_user }
  end

  def validate_add_attendant
    common_validate_attendant { @post.users.include? current_user or (@post.limited and @post.limit == @post.users.count) }
  end

  def build_post_filter
    @post_filter = Post.new post_filter_model_params
  end

  #used for scoping
  def post_search_params(pars)
    pars ||= {}
    pars[:time_to] = pars[:time_to].to_datetime.to_i unless pars[:time_to].nil? or pars[:time_to].empty?
    pars[:time_from] = pars[:time_from].to_datetime.to_i unless pars[:time_from].nil? or pars[:time_from].empty?
    pars[:attendants] = nil if pars[:attendants]&.first&.empty?
    pars[:attendants] = pars[:attendants][0].split(',').reject(&:empty?) unless pars[:attendants].nil?
    pars.slice :name, :time_from, :time_to, :attendants, :category_id, :city_name, :event_name
  end

  #user for populating filter form
  def post_filter_model_params
    params.require(:post).permit(:name, :time_from, :time_to, :category_id, :city_name,
                                 :event_name, :attendants => []) unless params[:post].nil?
  end
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer-container clear-fix">
<p class="pull-left">Hobist &copy; 2016</p>
<ul class="ul-horizontal pull-right">
  <li>
    <a href="#">O nás</a>
  </li>
  <li>
    <a href="#">Kontakt</a>
  </li>
</ul>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to '/', id: "logo" do %>
        Hobist
    <% end %>
    <nav>
      <ul class="nav navbar-nav">
        <li>
          <%= link_to 'Domov', root_path %>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Kategórie <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <% Category.find_each do |category| %>
                <li><%= link_to category.name, posts_path(post: {category_id: category.id}) %></li>
            <% end %>
            <li><%= link_to 'Všetky', posts_path %></li>
          </ul>
        </li>
        <% if user_signed_in? %>
            <li><%= link_to 'Upraviť profil', edit_user_registration_path(id: current_user.id) %></li>
            <li class="divider"></li>
            <li><%= link_to 'Odhlásiť', destroy_user_session_path, method: "delete" %></li>
        <% else %>
            <li><%= link_to 'Prihlásiť/Registrovať', new_user_session_path %></li>
        <% end %>
      </ul>

      <ul class="nav navbar-nav navbar-right navbar-inverse">
        <li>
          <div style="margin: 5px 10px;">
            <%= link_to '+ Vytvoriť udalosť', new_post_path, class: 'btn btn-primary' %>
          </div>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Filter <b class="caret"></b>
          </a>
          <div class="dropdown-menu dropdown-opened">
            <%= render partial: 'posts/post_filter' %>
          </div>
        </li>
        <li>
          <%= form_tag(posts_path, :method => 'get', id: 'search-form') do %>
              <%= text_field_tag :search, params[:search], class: 'search-query', placeholder: 'Hľadať', type:
                  'search', data: {} %>
              <%= image_submit_tag 'Hľadaj', :type => :image, :src => "/find_button.png", class: 'btn btn-primary' %>
          <% end %>
        </li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hobist</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>

<div class="container">
  <div class="jumbotron center">
    <% flash.each do |type, message| %>
        <div class="alert alert-<%= type %>"><p class="center"><%= message %></p></div>
    <% end %>
    <%= yield :form_errors %>
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
</div>

</body>
</html>

app/views/posts/_invite_form.html.erb
<%= form_tag posts_send_invitation_path(id: @post.id), method: :post do %>
    <%= autocomplete_field_tag 'Users', '', posts_autocomplete_user_name_path, 'data-delimiter' => ',', multiple: true %>
    <%= submit_tag 'Invite', class: 'btn btn-primary' %>
<% end %>

app/views/posts/_post.html.erb
<div class="post">
  <div class="postpanel">
    <%= link_to post do %>
        <div class="heading">
          <h4 class="title"><%= post.name %></h4>
          <p><b>Dátum:</b> <%= DateTime.strptime post.time.to_s, '%s' %></p>
          <p><b>Miesto:</b> <%= post.city.name %> : <%= post.locality %></p>
        </div>

        <div class="body">
          <% if post.picture.present? %>
            <%= image_tag post.picture.url %>
          <% else %>
            <p><%= strip_tags post.description[0,200] %></p>
          <% end %>
        </div>
    <% end %>
  </div>
</div>

app/views/posts/_post_filter.html.erb
<%= form_for @post_filter, method: :get, url: posts_path do |f| %>

    <%= label :event_name, 'Názov udalosti' %>
    <%= f.text_field :event_name %>

    <hr>
    <h5>Časové rozmedzie</h5>
    <%= label :time_from, 'Od' %>
    <%= f.text_field :time_from, class: 'datetimepicker' %>

    <%= label :time_to, 'Do' %>
    <%= f.text_field :time_to, class: 'datetimepicker' %>
    <hr>

    <%= label :attendants, 'Účastníci' %>
    <%= f.autocomplete_field :attendants, posts_autocomplete_user_name_path, 'data-delimiter' => ',', multiple: true %>

    <%= label :category, 'Kategória' %>
    <%= f.collection_select :category_id, Category.all, :id, :name, include_blank: true %>

    <%= label :city_name, 'Mesto' %>
    <%= f.autocomplete_field :city_name, posts_autocomplete_city_name_path %>

    <%= f.submit 'Hľadať', class: 'btn btn-primary' %>
<% end %>

<%= javascript_tag do %>
  $('.datetimepicker').datetimepicker({
    format : 'DD/MM/YYYY HH:mm'
  });
<% end %>

app/views/posts/_post_form.html.erb
<div class="row">
  <div class="container col-md-6 col-md-offset-3">
    <%= form_for @post, method: method do |f| %>
        <%= form_errors_for @post %>

        <%= f.label :name, 'Názov udalosti' %>
        <%= f.text_field :name, required: true %>

        <%= f.label :time_at, 'Čas konania udalosti' %>
        <%= f.text_field :time_at, class: 'datetimepicker', required: true %>

        <%= f.label :category, 'Kategória' %>
        <%= f.collection_select :category_id, Category.all, :id, :name, required: true %>

        <%= f.label :city_name, 'Mesto' %>
        <%= f.autocomplete_field :city_name, posts_autocomplete_city_name_path, id_element: '#city-id' %>
        <%= f.hidden_field :city_id, id: 'city-id' %>

        <%= f.label :locality, 'Lokalita' %>
        <%= f.text_field :locality, required: true %>

        <%= f.label :limit, 'Kapacita, 0 znamená bez obmedzenia' %>
        <%= f.number_field :limit, value: 0, min: 0, required: true %>

        <%= f.label :description, 'Popis udalosti' %>
        <%= f.bootsy_area :description, required: true %>

        <%= f.label :picture, 'Obrázok' %>
        <%= f.file_field :picture %>

        <%= f.submit submit, class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

<%= javascript_tag do %>
    $('.datetimepicker').datetimepicker({
    format : 'DD/MM/YYYY HH:mm'
    });
<% end %>

app/views/posts/edit.html.erb
<%= render partial: 'post_form', locals: {method: :patch, submit: 'Upraviť udalosť'} %>

app/views/posts/index.html.erb
<div class="row">

  <aside class="col-md-3">
    <%= render partial: 'posts/post_filter' %>
  </aside>

  <div class="col-md-9">
    <% unless @posts.any? %>
        <h3 class="center">Vašemu hladaniu nezodpovedá žiadna udalosť</h3>
    <% end %>
    <%= will_paginate @posts %>
    <% @posts.each_with_index do |post, idx| %>
        <% if idx % 3 == 0 %>
            <div class="row">
        <% end %>
        <%= render partial: 'posts/post', locals: {post: post} %>
        <% if idx % 3 == 2 %>
            </div>
        <% end %>
    <% end %>
    <% if @posts.count % 3 != 0 %>
        </div>
    <% end %>
    <%= will_paginate @posts %>
    </div>

</div>

app/views/posts/new.html.erb
<%= render partial: 'post_form', locals: {method: :post, submit: 'Vytvoriť udalosť'} %>

app/views/posts/show.html.erb
<h1><%= @post.name %></h1>
<div class="row">

  <div class="col-md-6">
    <h3 class="left"><b>Dátum:</b> <%= Date.strptime @post.time.to_s, '%s' %></h3>
    <h3 class="left"><b>Čas:</b> <%= Time.strptime(@post.time.to_s, '%s').strftime '%H:%M' %></h3>
  </div>

  <div class="col-md-6">
    <h3 class="right">
      <% if @post.limited %>
          Kapacita: <%= @post.users.count %>/<%= @post.limit %>
      <% else %>
          Počet zúčastnených: <%= @post.users.count %>
      <% end %>
    </h3>
  </div>

</div>

<div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <%= render partial: 'posts/invite_form' %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <% if current_user? @post.user_id %>
        <%= link_to 'Upraviť udalosť', edit_post_path(@post), method: :get, class: 'postButton' %>
        <%= link_to 'Odstrániť udalosť', post_path(@post), method: :delete, class: 'postButton' %>
    <% end %>
    <% unless current_user.nil? %>
        <button type="button" class="postButton" data-toggle="modal" data-target=".bs-example-modal-lg">Invite</button>
    <% end %>
    <% if current_user.nil? %>
        <%= link_to 'Prihlásiť sa', new_user_session_path, class: 'postButton' %><br/>prihláste sa na to, aby ste sa mohli zučastniť
    <% elsif @post.users.exclude? current_user %>
        <%= link_to 'Zúčastniť sa', posts_add_attendant_path(id: @post.id), class: 'postButton', method: :post %>
    <% else %>
        <%= link_to 'Nezúčastniť sa', posts_remove_attendant_path(id: @post.id), class: 'postButton',
                    method: :delete %>
    <% end %>
  </div>
</div>

<div class="row" style="margin-top:20px">

  <div class="col-md-6">
    <div id="map" class="map"></div>
  </div>

  <div class="col-md-6">
    <div class="col-md-12 panel panel-body">
      <%= raw @post.description %>
    </div>

    <div class="col-md-12 panel panel-body">
      <p>Email tvorcu udalosti: </p>
      <%= mail_to @post.user.email, @post.user.email %>
    </div>
  </div>

</div>

<%= content_tag :div, class: 'locality-content', data: {locality: @post.locality, city: @post.city.name} do %>
<% end %>
<%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=AIzaSyABIzzN7SlW5GoZk7xOoBziqObZRw9TzsU&libraries=geometry&callback=initActivityMap", defer: 'defer', async: 'async' %>

app/views/shared/_form_errors.html.erb
<% content_for :form_errors do %>
    <p>
      <%= pluralize(object.errors.count, 'error') %> zabránlo uloženiu formulára:
    </p>

    <ul>
      <% object.errors.full_messages.each do |message| %>
          <li><%= message %></li>
      <% end %>
    </ul>
<% end %>